### ISSUE TITLE
Example on creating a proper wasm file

### ISSUE THREAD

**Issue by koenvo** [miracle2k/wasmbind#1]
Hi,

Thanks for this really interesting library. This is a great step for writing code that can run in the browser and in a python backend!

I was wondering if you can share an example of how to compile WebAssembly so it's loadable by python-ext-wasm. I know this issue might be unrelated to this library.

I tried this:
1. install the`assemblyscript` npm package
2. start a new assemblyscript project: `npx asinit sometest`
3. build the index.ts file using `npm run-script asbuild`

When I try to load the file I keep getting:
```sh
Traceback (most recent call last):
  File "tests/wasm/test.py", line 7, in <module>
    wasm = Instance(code)
RuntimeError: Failed to instantiate the module:
    link error: Import not found, namespace: env, name: abort
```

It looks like it's related to "Support imports (needs #28)" but I'm confused by your example which doesn't do anything with imports.

```python
from wasmer import Instance
wasm = Instance(open('yourscript.wasm', 'rb').read())

from wasmbind import Module
module = Module(wasm)
```

Could you share a some info on how to create a proper .wasm file?

Thanks a lot!

**Comment by miracle2k** [comment]
Yeah, when you compile webassembly you need to disable the abort import using `--use  abort=`.

This is the command line I used:

```
npx assemblyscript lib/fixCaptionTrack.ts -b fixers.wasm --use  abort=
```

Actually, support for imports was recently merged into `python-ext-wasm`, so we could actually provide that import now.

**Comment by koenvo** [comment]
That's great! thanks a lot.

I saw it was merged :-) I would like to install `python-ext-wasm` using pip instead of building it from source.

[edit]
I see it's also in the tests.. doh
[/edit]

**Comment by koenvo** [comment]
I still get an error when I specify `--use abort=`:

```sh
koen$ cat /tmp/main.ts 
export function helloworld(s: string): string {
        return "foo:" + s
}
````

```sh
koen$ npx assemblyscript /tmp/main.ts -b --use abort= > /tmp/output.wasm
npx: installed 3 in 4.285s
ERROR: AssertionError: assertion failed
    at t.assert (/Users/koen/.npm/_npx/27619/lib/node_modules/assemblyscript/dist/assemblyscript.js:7:576726)
    at g.initialize (/Users/koen/.npm/_npx/27619/lib/node_modules/assemblyscript/dist/assemblyscript.js:7:44520)
    at Object.t.initializeProgram (/Users/koen/.npm/_npx/27619/lib/node_modules/assemblyscript/dist/assemblyscript.js:7:594197)
    at stats.compileTime.measure (/Users/koen/.npm/_npx/27619/lib/node_modules/assemblyscript/cli/asc.js:595:22)
    at measure (/Users/koen/.npm/_npx/27619/lib/node_modules/assemblyscript/cli/asc.js:1103:3)
    at Object.main (/Users/koen/.npm/_npx/27619/lib/node_modules/assemblyscript/cli/asc.js:594:26)
    at asc.ready.then (/Users/koen/.npm/_npx/27619/lib/node_modules/assemblyscript/bin/asc:21:47)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:52:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at findNodeScript.then.existing (/Users/koen/.nvm/versions/node/v11.15.0/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
```

```sh
koen$ npx assemblyscript -v
Version 0.9.4
```

**Comment by miracle2k** [comment]
Hm - I think you have to open a ticket with AssemblyScript here, seems like a bug on their side. I've run into assertion errors myself, though this seems like to easy a function to cause them.

Note that overriding the abort function [is documented](https://docs.assemblyscript.org/details/debugging#overriding-abort) and should be officially supported.

**Comment by koenvo** [comment]
You are right. Found the issue on their side: 
https://github.com/AssemblyScript/assemblyscript/issues/1176 (and PR: https://github.com/AssemblyScript/assemblyscript/pull/1177 )

This works:
```sh
koen$ npx assemblyscript@0.9.4-nightly.20200430 /tmp/main.ts -b --use abort= > /tmp/output.wasm
```
